apiVersion: v1
kind: ConfigMap
metadata:
  name: mds-appsettings
data:
  appsettings.prod.json: |-
    ##PROD_SETTINGS##
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mds-jobsettings
data:
  jobsettings.prod.json: |-
    ##PROD_JOB_SETTINGS##
