apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ids-service
  name: ids-service-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ids-service
  template:
    metadata:
      labels:
        app: ids-service
    spec:
      containers:
      - name: ids-service
        image: ##IDS_SERVICE_IMAGE##
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: K8Pod
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: app-settings-config-volume
          mountPath: /app/Config
      volumes:
      - name: app-settings-config-volume
        configMap:
          name: ##APP_SETTINGS_CONFIGMAP##
---
kind: Service
apiVersion: v1
metadata:
  name: ids-service-service
  namespace: default
  labels:
    svc: ids-service-service
spec:
  selector:
    app: ids-service
  ports:
  - name: http
    protocol: TCP
    port: 8001
  type: LoadBalancer
