apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdsservice-deployment
  labels:
    app: mdsservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdsservice
  template:
    metadata:
      labels:
        app: mdsservice
    spec:
      volumes:
        - name: mds-appsettings-volume
          configMap:
            name: mds-appsettings
        - name: mds-jobsettings-volume
          configMap:
            name: mds-jobsettings
      containers:
        - name: mdsservice
          image: ##imagename##
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mds-appsettings-volume
              mountPath: /app/appsettings.prod.json
              subPath: appsettings.prod.json
          imagePullPolicy: Always
        - name: mdsworkerservice
          image: ##workerimagename##
          volumeMounts:
            - name: mds-jobsettings-volume
              mountPath: /app/jobsettings.prod.json
              subPath: jobsettings.prod.json
          imagePullPolicy: Always
      nodeSelector:
        agentpool: apppool
---
apiVersion: v1
kind: Service
metadata:
  name: mdsservice-loadbalancer-service
  labels:
    app: mdsservice
spec:
  type: LoadBalancer
  selector:
    app: mdsservice
  ports:
    - port: 80
      targetPort: 80
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appinsights-k8s-property-reader
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "nodes", "replicasets", "deployments"]
  verbs: ["get", "list"]
---
# actual binding to the role
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appinsights-k8s-property-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: appinsights-k8s-property-reader
  apiGroup: rbac.authorization.k8s.io
